#!/usr/bin/env ruby

###############################
# BILLmanager Ticket Notifier #
#         (BiTiNo)            #
###############################
#       file: bitinod         #
###############################

## This is a daemon controller for BiTiNo.
require 'daemons'

Daemons.run('bitino.rb')
